org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.123
neo_version_range=[21,)
loader_version_range=[2,)
loader_type=neoforge

mod_id=sakura_sign_in
mod_name=\u6a31\u82b1\u7b7e
mod_license=MIT
mod_version=2.0.0-alpha.2
mod_group_id=xin.vanilla.sakura
mod_authors=Tsuki Maaii
mod_description=

banira_version=1.0.3
banira_version_range=[1.0.3,1.1.0)
